version: '3'

services:

  web_test:
    container_name: web_test
    restart: always
    build: ./web_test
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 app:server


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web_test